development:
  :use_ssl => false,
  :dynamo_db_endpoint => 'localhost',
  :dynamo_db_port => 4567,
  :access_key_id => "xxx",
  :secret_access_key => "xxx"

test:
  <<: *development

production:
  <<: *development