development:
  use_ssl: false
  dynamo_db_endpoint: 'localhost'
  dynamo_db_port: 4567
  access_key_id: "abc"
  secret_access_key: "123"

test:
  use_ssl: false
  dynamo_db_endpoint: 'localhost'
  dynamo_db_port: 4567
  access_key_id: "abc"
  secret_access_key: "123"

production:
  use_ssl: false
  dynamo_db_endpoint: 'localhost'
  dynamo_db_port: 8000
  access_key_id: "abc"
  secret_access_key: "123"